linter:
  rules:
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    # - avoid_types_as_parameter_names
    - empty_statements
    - throw_in_finally
    - unnecessary_statements
    - unsafe_html
    - valid_regexps
    - always_declare_return_types
    - always_put_control_body_on_new_line
    # - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    # - avoid_as
    - avoid_catching_errors
    # - avoid_catches_without_on_clauses
    - avoid_double_and_int_checks
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - file_names
    - non_constant_identifier_names
    - hash_and_equals
    - prefer_is_not_empty
