class Skills {
  List<String> _skills = [
    '.Net',
    '360-Degree Video',
    '3D Animation',
    '3D Design',
    '3D Model Maker',
    '3D Modelling',
    '3D Printing',
    '3D Rendering',
    '3DS Max',
    '4D',
    'Academic Writing',
    'Accounting',
    'Actionscript',
    'Active Directory',
    'Ad Planning / Buying',
    'Adobe Air',
    'Adobe Captivate',
    'Adobe Dreamweaver',
    'Adobe Fireworks',
    'Adobe Flash',
    'Adobe InDesign',
    'Adobe Lightroom',
    'Adobe Livecycle Designer',
    'Adobe Premiere Pro',
    'Advertisement Design',
    'Advertising',
    'Aeronautical Engineering',
    'Aerospace Engineering',
    'Affiliate Marketing',
    'Afrikaans',
    'After Effects',
    'Agile Development',
    'Agronomy',
    'Air Conditioning',
    'Airbnb',
    'AJAX',
    'Albanian',
    'Algorithm',
    'Alibaba',
    'Amazon Fire',
    'Amazon Kindle',
    'Amazon Web Services',
    'AMQP',
    'Analytics',
    'Android',
    'Android Honeycomb',
    'Android Wear SDK',
    'Angular',
    'Angular.js',
    'Animation',
    'Antenna Services',
    'Anything Goes',
    'Apache',
    'Apache Ant',
    'Apache SOLR',
    'App Designer',
    'App Developer',
    'Appcelerator Titanium',
    'Apple Compressor',
    'Apple iBooks Author',
    'Apple Logic Pro',
    'Apple Motion',
    'Apple Safari',
    'Apple Watch',
    'Applescript',
    'Appliance Installation',
    'Appliance Repair',
    'Arabic',
    'Arduino',
    'Argus Monitoring Software',
    'Article Rewriting',
    'Article Submission',
    'Articles',
    'Artificial Intelligence',
    'Arts/Crafts',
    'As400/Iseries',
    'Asbestos Removal',
    'ASP',
    'ASP.net',
    'Asphalt',
    'Assembly',
    'Asterisk PBX',
    'Astrophysics',
    'Attic Access Ladders',
    'Attorney',
    'Audio Production',
    'Audio Services',
    'Audit',
    'Augmented Reality',
    'Autocad',
    'Autodesk Inventor',
    'Autodesk Revit',
    'Autohotkey',
    'Automotive',
    'Autotask',
    'Awnings',
    'AWS',
    'Axure',
    'Azure',
    'B2B Marketing',
    'B2C Marketing',
    'Backbone.js',
    'Balsamiq',
    'Balustrading',
    'Bamboo Flooring',
    'Banner Design',
    'Basque',
    'Bathroom',
    'Bengali',
    'Big Data',
    'Bigcommerce',
    'Binary Analysis',
    'Biology',
    'Biotechnology',
    'Bitcoin',
    'Biztalk',
    'Blackberry',
    'Blog',
    'Blog Design',
    'Blog Install',
    'Bluetooth Low Energy (BLE)',
    'BMC Remedy',
    'Book Artist',
    'Book Writing',
    'Bookkeeping',
    'Boonex Dolphin',
    'Bootstrap',
    'Bosnian',
    'Bower',
    'BPO',
    'Brackets',
    'Brain Storming',
    'Branding',
    'Bricklaying',
    'Broadcast Engineering',
    'Brochure Design',
    'BSD',
    'Building',
    'Building Architecture',
    'Building Certifiers',
    'Building Consultants',
    'Building Designer',
    'Building Surveyors',
    'Bulgarian',
    'Bulk Marketing',
    'Business Analysis',
    'Business Cards',
    'Business Catalyst',
    'Business Coaching',
    'Business Intelligence',
    'Business Plans',
    'Business Writing',
    'Buyer Sourcing',
    'C',
    'C Programming',
    'C#',
    'C# Programming',
    'C++',
    'C++ Programming',
    'CAD/CAM',
    'CakePHP',
    'Call Center',
    'Call Control XML',
    'Capture NX2',
    'Caricature',
    'Carpentry',
    'Carpet Repair/Laying',
    'Carports',
    'Cartography/Maps',
    'Cartoons',
    'Car washing',
    'Casperjs',
    'Cassandra',
    'Catalan',
    'Catch Phrases',
    'Catia',
    'Ceilings',
    'Cement Bonding Agents',
    'CGI',
    'Chef',
    'Chef Configuration Management',
    'Chemical Engineering',
    'Chordiant',
    'Christmas',
    'Chrome OS',
    'Cinema 4D',
    'Circuit Design',
    'Cisco',
    'Civil Engineering',
    'Classifieds Posting',
    'Clean Technology',
    'Cleaning Carpet',
    'Cleaning Domestic',
    'Cleaning Upholstery',
    'Climate Sciences',
    'Clips',
    'Clothesline',
    'Cloud Computing',
    'CMS',
    'Coating Materials',
    'Cobol',
    'Cocoa',
    'Codeigniter',
    'Coding',
    'Cold Fusion',
    'Columns',
    'Commercial Cleaning',
    'Commercials',
    'Communications',
    'Compliance',
    'Computer Graphics',
    'Computer Help',
    'Computer Security',
    'Concept Art',
    'Concept Design',
    'Concreting',
    'Construction Monitoring',
    'Content Marketing',
    'Content Writing',
    'Contracts',
    'Conversion Rate Optimisation',
    'Cooking/Baking',
    'Cooking/Recipes',
    'Copy Typing',
    'Copywriting',
    'Corporate Identity',
    'Courses',
    'Covers/Packaging',
    'CRE Loaded',
    'Creative Design',
    'Creative Writing',
    'CRM',
    'Croatian',
    'Cryptography',
    'Crystal Reports',
    'CS-Cart',
    'CSS',
    'Cubecart',
    'Cuda',
    'Customer Service',
    'Customer Support',
    'Czech',
    'Damp Proofing',
    'Danish',
    'Dart',
    'Data Entry',
    'Data Mining',
    'Data Processing',
    'Data Science',
    'Data Warehousing',
    'Database Administration',
    'Database Development',
    'Database Programming',
    'Datalife Engine',
    'Dating',
    'DDS',
    'Debian',
    'Debugging',
    'Decking',
    'Decoration',
    'Delivery',
    'Delphi',
    'Demand Generation',
    'Demolition',
    'Design',
    'Desktop Support',
    'DevOps',
    'Digital Design',
    'Disposals',
    'Django',
    'DNS',
    'Docker',
    'DOS',
    'Dotnetnuke',
    'Drafting',
    'Drains',
    'Drones',
    'Drupal',
    'D3js',
    'Dthreejs',
    'Dutch',
    'Dynamics',
    'Ebay',
    'Ebooks',
    'Ecommerce',
    'Editing',
    'Education/Tutoring',
    'EDX',
    'Elasticsearch',
    'Elearning',
    'Elearning Designer',
    'Electrical Engineering',
    'Electricians',
    'Electronic Forms',
    'Electronics',
    'Elixir',
    'Eloqua',
    'Email Developer',
    'Email Handling',
    'Email Marketing',
    'Embedded Software',
    'Ember.js',
    'Employment Law',
    'Energy',
    'Engineering',
    'Engineering Drawing',
    'English (UK)',
    'English (US)',
    'English Grammar',
    'English Spelling',
    'Entrepreneurship',
    'EPUB',
    'Equipment Hire',
    'Erlang',
    'ERP',
    'ES6',
    'Estonian',
    'Etsy',
    'Event Marketing',
    'Event Planning',
    'Event Staffing',
    'Excavation',
    'Excel',
    'Express JS',
    'Expression Engine',
    'Extensions/Additions',
    'Face Recognition',
    'Facebook Marketing',
    'Fashion Design',
    'Fashion Modeling',
    'Fencing',
    'Feng Shui',
    'Fiction',
    'Filemaker',
    'Filipino',
    'Filmmaking',
    'Final Cut Pro',
    'Finale/Sibelius',
    'Finance',
    'Financial Analysis',
    'Financial Markets',
    'Financial Planning',
    'Financial Research',
    'Finite Element Analysis',
    'Finnish',
    'Firefox',
    'Flash 3D',
    'Flashmob',
    'Flex',
    'Floor Coatings',
    'Flooring',
    'Flow Charts',
    'Flyer Design',
    'Flyscreens',
    'Food Takeaway',
    'Format/Layout',
    'Fortran',
    'Forum Posting',
    'Forum Software',
    'FPGA',
    'Frames/Trusses',
    'Freelance',
    'FreelancerAPI',
    'Freeswitch',
    'French',
    'French (Canadian)',
    'Fundraising',
    'Furniture Assembly',
    'Furniture Design',
    'Game Consoles',
    'Game Design',
    'Game Development',
    'GameSalad',
    'Gamification',
    'GarageBand',
    'Gardening',
    'Gas Fitting',
    'Genealogy',
    'General Labor',
    'General Office',
    'Genetic Engineering',
    'Geolocation',
    'Geology',
    'Geospatial',
    'Geotechnical Engineering',
    'German',
    'Ghostwriting',
    'GIMP',
    'Git',
    'Glass/Mirror/Glazing',
    'Go Lang',
    'Golang',
    'Google Adsense',
    'Google Adwords',
    'Google Analytics',
    'Google App Engine',
    'Google Cardboard',
    'Google Chrome',
    'Google Cloud',
    'Google Cloud Storage',
    'Google Earth',
    'Google Maps API',
    'Google Plus',
    'Google Sketchup',
    'Google Tag Manager',
    'Google Web Toolkit',
    'Google Webmaster Tools',
    'Google Website Optimizer',
    'GoPro',
    'GPGPU',
    'GPS',
    'Grails',
    'Grant Writing',
    'Graphic Design',
    'Grease Monkey',
    'Greek',
    'Growth Hacking',
    'Grunt',
    'Guttering',
    'Hadoop',
    'Hair Styling',
    'Handyman',
    'Haskell',
    'HBase',
    'Health',
    'Heating Systems',
    'Hebrew',
    'Helpdesk',
    'Heroku',
    'Hindi',
    'Hire Me',
    'History',
    'Hive',
    'Home Automation',
    'Home Design',
    'Home Organization',
    'HomeKit',
    'Hot Water',
    'House Cleaning',
    'Housework',
    'HP Openview',
    'HTML',
    'HTML5',
    'Human Resources',
    'Human Sciences',
    'Hungarian',
    'iBeacon',
    'IBM BPM',
    'IBM Tivoli',
    'IBM Websphere Transformation Tool',
    'Icon Design',
    'IIS',
    'Ikea Installation',
    'Illustration',
    'Illustrator',
    'Imaging',
    'iMovie',
    'Indonesian',
    'Industrial Design',
    'Industrial Engineering',
    'Infographics',
    'Inspections',
    'Instagram',
    'Installation',
    'Instrumentation',
    'Insurance',
    'Interior Design',
    'Interiors',
    'Internet Marketing',
    'Internet Research',
    'Internet Security',
    'Interpreter',
    'Interspire',
    'Intuit Quickbooks',
    'Inventory Management',
    'Investment Research',
    'Invitation Design',
    'Ionic Framework',
    'iOS',
    'iPad',
    'iPhone',
    'ISO9001',
    'Italian',
    'Itil',
    'J2EE',
    'J2ME',
    'Jabber',
    'Japanese',
    'Java',
    'JavaFX',
    'JavaScript',
    'JDF',
    'Jenkins',
    'Jewellery',
    'Joomla',
    'Journalist',
    'jQuery/Prototype',
    'JSON',
    'JSP',
    'Kafka',
    'Kannada',
    'Kinect',
    'Kitchen',
    'Knockout.js',
    'Korean',
    'Kotlin',
    'Kubernetes',
    'Label Design',
    'LabView',
    'Landing Pages',
    'Landscape Design',
    'Landscaping',
    'Landscaping/Gardening',
    'Laravel',
    'Latex',
    'Latvian',
    'Laundry And Ironing',
    'Lawn Mowing',
    'Leads',
    'Leap Motion SDK',
    'Legal',
    'Legal Research',
    'Legal Writing',
    'Less/SASS/SCSS',
    'Life Coaching',
    'Lighting',
    'Linear Programming',
    'Link Building',
    'LinkedIn',
    'Linnworks Order Management',
    'Linq',
    'Linux',
    'Lisp',
    'Lithuanian',
    'Livecode',
    'Locksmith',
    'Logistics/Shipping',
    'Logo Design',
    'Lotus Notes',
    'Lua',
    'Mac OS',
    'Macedonian',
    'Machine Learning',
    'Magento',
    'Magic Leap',
    'Mailchimp',
    'Mailwizz',
    'Makeup',
    'Makerbot',
    'Malay',
    'Malayalam',
    'Maltese',
    'Management',
    'Manufacturing',
    'Manufacturing Design',
    'Map Reduce',
    'Mapreduce',
    'MariaDB',
    'Market Research',
    'Marketing',
    'Marketing Automation',
    'Marketo',
    'Marketplace Service',
    'Materials Engineering',
    'Mathematics',
    'Matlab And Mathematica',
    'Maya',
    'Mechanical Engineering',
    'Mechatronics',
    'Medical',
    'Medical Writing',
    'Metatrader',
    'MeteorJS',
    'Metro',
    'Microbiology',
    'Microcontroller',
    'Microsoft',
    'Microsoft Access',
    'Microsoft Azure',
    'Microsoft Exchange',
    'Microsoft Expression',
    'Microsoft Hololens',
    'Microsoft Office',
    'Microsoft Outlook',
    'Microsoft Sql Server',
    'Microsoft Visio',
    'Microstation',
    'Millwork',
    'Mining Engineering',
    'Minitlab',
    'MLM',
    'MMORPG',
    'Mobile App Testing',
    'Mobile Design',
    'Mobile Phone',
    'MODX',
    'MonetDB',
    'MongoDB',
    'Moodle',
    'Mortgage Brokering',
    'Motion Graphics',
    'Moving',
    'MQTT',
    'Mural Painting',
    'Music',
    'MVC',
    'MYOB',
    'MySpace',
    'MySQL',
    'Nanotechnology',
    'Natural Language',
    'Network Administration',
    'Newsletters',
    'Nginx',
    'Ning',
    'Nintex Forms',
    'Nintex Workflow',
    'Node.js',
    'Nokia',
    'Norwegian',
    'NoSQL Couch / Mongo',
    'Nutrition',
    'OAuth',
    'Objective-C',
    'OCR',
    'Oculus Mobile SDK',
    'Odoo',
    'Online Writing',
    'Open Cart',
    'Open Journal Systems',
    'Openbravo',
    'OpenCL',
    'OpenGL',
    'OpenSceneGraph',
    'OpenSSL',
    'OpenStack',
    'OpenVMS',
    'Oracle',
    'Order Processing',
    'Organizational Change Management',
    'OsCommerce',
    'Package Design',
    'Packing/Shipping',
    'Paid Social',
    'Painting',
    'Palm',
    'Papiamento',
    'Parallax Scrolling',
    'Parallel Processing',
    'Parallels Automation',
    'Parallels Desktop',
    'Pardot',
    'Patents',
    'Pattern Making',
    'Pattern Matching',
    'Pavement',
    'Pay Per Click',
    'Paypal API',
    'Payroll',
    'PayTrace',
    'PCB Layout',
    'PDF',
    'Pega PRPC',
    'Pencilblue CMS',
    'Pentaho',
    'PeopleSoft',
    'Periscope',
    'Perl',
    'Personal Development',
    'Pest Control',
    'Pet Sitting',
    'Petroleum Engineering',
    'Phone Support',
    'Phonegap',
    'Photo Editing',
    'Photography',
    'Photoshop',
    'Photoshop Coding',
    'Photoshop Design',
    'PHP',
    'Physics',
    'Pick Multivalue DB',
    'Pickup',
    'Pinterest',
    'Piping',
    'PLC/Scada',
    'Plesk',
    'Plugin',
    'Plumbing',
    'Poet',
    'Poetry',
    'Polish',
    'Portuguese',
    'Portuguese (Brazil)',
    'Post-Production',
    'Poster Design',
    'PostgreSQL',
    'PowerPoint',
    'PowerShell',
    'Pre-Production',
    'Presentations',
    'Press Releases',
    'Prestashop',
    'Prezi',
    'Print',
    'Procurement',
    'Product Descriptions',
    'Product Design',
    'Product Management',
    'Product Marketing',
    'Product Sourcing',
    'Programmatic Display Advertising',
    'Programming',
    'Project Management',
    'Project Scheduling',
    'Prolog',
    'Proofreading',
    'Property Development',
    'Property Law',
    'Property Management',
    'Proposal/Bid Writing',
    'Protoshare',
    'Psd To Html',
    'PSD2CMS',
    'Psychology',
    'Public Relations',
    'Publishing',
    'Punjabi',
    'Puppet',
    'Python',
    'Qlikview',
    'Qualtrics Survey Platform',
    'Quantum',
    'Quarkxpress',
    'Quickbase',
    'R',
    'R Programming Language',
    'Rapidweaver',
    'Raspberry Pi',
    'Ray-Tracing',
    'React.js',
    'Real Estate',
    'RealBasic',
    'Recruitment',
    'Red Hat',
    'Redis',
    'Redshift',
    'Regular Expressions',
    'Remote Sensing',
    'Removalist',
    'Renewable Energy Design',
    'Report Writing',
    'Research',
    'Restful',
    'Resumes',
    'Reviews',
    'Risk Management',
    'Robotics',
    'Rocket Engine',
    'Romanian',
    'Roofing',
    'RTOS',
    'Ruby',
    'Ruby On Rails',
    'Russian',
    'RWD',
    'Sales',
    'SalesForce',
    'SalesForce App Development',
    'SalesForce.com',
    'Samsung',
    'Samsung Accessory SDK',
    'SAP',
    'SAS',
    'Scala',
    'Scheme',
    'Scientific Research',
    'Screenwriting',
    'Script Install',
    'Scrum',
    'Scrum Development',
    'Sculpturing',
    'Search Engine Marketing',
    'Segment',
    'Sem',
    'Sencha/YahooUI',
    'SEO',
    'Serbian',
    'Serverless',
    'Sewing',
    'Sharepoint',
    'Shell Script',
    'Shopify',
    'Shopify Templates',
    'Shopping',
    'Shopping Carts',
    'Short Stories',
    'Siebel',
    'Sign Design',
    'SilverLight',
    'Simplified Chinese (China)',
    'Sketch',
    'Slogans',
    'Slovakian',
    'Slovenian',
    'Smarty PHP',
    'Snapchat',
    'Social Engine',
    'Social Media Marketing',
    'Social Networking',
    'Socket IO',
    'Software Architecture',
    'Software Development',
    'Software Testing',
    'Solaris',
    'Solidworks',
    'Sound Design',
    'Spanish',
    'Spanish (Spain)',
    'Spark',
    'Speech Writing',
    'Sphinx',
    'Splunk',
    'Sports',
    'Spss Statistics',
    'SQL',
    'SQL Server',
    'SQLite',
    'Squarespace',
    'Squid Cache',
    'Startups',
    'Stationery Design',
    'Statistical Analysis',
    'Statistics',
    'Steam API',
    'Sticker Design',
    'Storage Area Networks',
    'Storyboard',
    'Stripe',
    'Structural Engineering',
    'Subversion',
    'SugarCRM',
    'Supplier Sourcing',
    'Surfboard Design',
    'Swedish',
    'Swift',
    'Symbian',
    'Symfony PHP',
    'Symphony',
    'System Admin',
    'T-Shirts',
    'Tableau',
    'Tally Definition Language',
    'Tamil',
    'Taobao API',
    'Tattoo Design',
    'Tax',
    'Tax Law',
    'Technical Support',
    'Technical Writing',
    'Tekla Structures',
    'Telecommunications Engineering',
    'Telemarketing',
    'Telephone Handling',
    'Telugu',
    'Templates',
    'Test Automation',
    'Testing/QA',
    'TestStand',
    'Textile Engineering',
    'Thai',
    'Tibco Spotfire',
    'Tiling',
    'Time Management',
    'Titanium',
    'Tizen SDK For Wearables',
    'Traditional Chinese (Hong Kong)',
    'Traditional Chinese (Taiwan)',
    'Training',
    'Transcription',
    'Translation',
    'Travel Writing',
    'Troubleshooting',
    'Tumblr',
    'Turkish',
    'Twitter',
    'Typescript',
    'Typo3',
    'Typography',
    'Ubuntu',
    'UI Design',
    'Ukrainian',
    'Umbraco',
    'UML Design',
    'Unit4 Business World',
    'Unity 3D',
    'Unix',
    'Urdu',
    'Usability Testing',
    'User Experience Design',
    'User Interface / IA',
    'User Interface Design',
    'UX Design',
    'Valuation/Appraisal',
    'Varnish Cache',
    'VB.net',
    'vBulletin',
    'Vectorization',
    'Veeam',
    'Vehicle Signage',
    'Verilog',
    'Vertexfx',
    'VHDL',
    'Video Broadcasting',
    'Video Editing',
    'Video Production',
    'Video Services',
    'Video Upload',
    'Videography',
    'Vietnamese',
    'Viral Marketing',
    'Virtual Assistant',
    'Virtual Worlds',
    'Virtuemart',
    'Virtuozzo',
    'Visa/Immigration',
    'Visual Arts',
    'Visual Basic',
    'Visual Basic For Apps',
    'Visual Foxpro',
    'Visual Merchandising',
    'Visualization',
    'VMWare',
    'Voice Artist',
    'Voice Talent',
    'VoiceXML',
    'Voip',
    'Volusion',
    'Vps',
    'Vtiger',
    'Vue.js',
    'Vuforia',
    'WatchKit',
    'Web Hosting',
    'Web Scraping',
    'Web Search',
    'Web Security',
    'Web Services',
    'WebMethods',
    'WebOS',
    'Website Design',
    'Website Management',
    'Website Testing',
    'Weddings',
    'Weebly',
    'Welsh',
    'WHMCS',
    'Wiki',
    'Wikipedia',
    'Windows 8',
    'Windows API',
    'Windows CE',
    'Windows Desktop',
    'Windows Mobile',
    'Windows Phone',
    'Windows Server',
    'Wireframes',
    'Wireless',
    'Wix',
    'Wolfram',
    'Woocommerce',
    'Word',
    'Word Processing',
    'Wordpress',
    'Workshops',
    'WPF',
    'Wufoo',
    'X86/X64 Assembler',
    'Xamarin',
    'Xero',
    'XML',
    'XMPP',
    'Xojo',
    'Xoops',
    'XPages',
    'XQuery',
    'XSLT',
    'Yahoo! Store Design',
    'Yard Work / Removal',
    'Yarn',
    'Yiddish',
    'Yii',
    'Youtube',
    'ZBrush',
    'Zen Cart',
    'Zend',
    'Zoho'
  ];

  List<String> get getSkills {
    return [..._skills];
  }
}
